macro(export_gtest)
    if (NOT GTEST_EXPORTED)
        find_package(GTest REQUIRED)
        if(NOT GTest_FOUND)
            message("Failed to find GTest")
            return()
        else()
            message("GTest Exported")
            set(GTEST_EXPORTED "YES")
        endif()
    endif()
endmacro()